name: Build Maven Backend

on:
  pull_request:
    branches: [ "feature/cicd" ]

env:
  BACKEND_PATH: "backend"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.BACKEND_PATH }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and Run Tests
      run: mvn test --batch-mode --fail-at-end
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1