name: Build and Test Maven Backend

on:
  push:
    branches: [ "feature/packaging" ]

env:
  BACKEND_PATH: "backend"
  FRONTEND_PATH: "frontend"

jobs:
  package-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.BACKEND_PATH }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Package project
      run: mvn package
  build-frontend:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          package_root: ${{ env.FRONTEND_PATH }}

          args: "--publish never"

          # # If the commit is tagged with a version (e.g. "v1.0.0"),
          # # release the app after building
          # release: ${{ startsWith(github.ref, 'refs/tags/v') }} 
  