name: Test Backend Pull Request

on:
  # pull_request:
  #   branches: [ "develop" ]
  push:
      branches: ["feature/frontend_cicd"]

env:
  BACKEND_PATH: "backend"
  FRONTEND_PATH: "frontend"

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.BACKEND_PATH }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build project
      run: mvn compile
    - name: Run Tests
      run: mvn test --batch-mode --fail-at-end
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_PATH }}
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
